version: '3' 
services:
    db:
        image: postgres
        expose:
            - "5432"
        environment:
            POSTGRES_DB: todo_db
            POSTGRES_USER: todo_admin
            POSTGRES_PASSWORD: todo_password
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "./postgres/pgdata:/var/lib/postgresql/data/pgdata" # persist the data
            - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d" # execute sql in here (see https://hub.docker.com/_/postgres)
    postgrest:
        image: postgrest/postgrest
        ports:
            - "3000:3000"
        environment:
            PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/todo_db
            PGRST_DB_SCHEMA: api
            PGRST_DB_ANON_ROLE: web_anon
            PGRST_JWT_SECRET: ${TODO_SECRET}
            PGRST_OPENAPI_SERVER_PROXY_URI: ${PGRST_OPENAPI_SERVER_PROXY_URI}
        depends_on:
            - db
    postgrest-proxy:
        depends_on:
            - postgrest
        image: nginx:latest
        ports:
            - "3001:3001"
        volumes:
            - "./postgrest-proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        expose:
            - "8080"
        depends_on: 
            - postgrest-proxy
        environment:
            API_URL: ${PGRST_OPENAPI_SERVER_PROXY_URI}
