version: '3' 
services:
    postgrest:
        image: postgrest/postgrest
        ports:
            - "3000:3000"
        environment:
            PGRST_DB_URI: ${PGRST_DB_URI}
            PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
            PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
            PGRST_JWT_SECRET: ${TODO_SECRET}
    postgrest-proxy:
        depends_on:
            - postgrest
        image: nginx:latest
        ports:
            - "3001:3001"
        volumes:
            - "./postgrest-proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        expose:
            - "8080"
        depends_on: 
            - postgrest-proxy
        environment:
            API_URL: http://localhost:3001/
